const USER_COLLECTION = "User"
const MOVIE_COLLECTION = "Movie"
const COMMENT_COLLECTION = "Comment"
const RATING_COLLECTION = "Rating"
const LIKES_COLLECTION = "Likes"

const PERMISSION_DENIED = "Permissão negada."
const ACCESS_DENIED = "Acesso negado."

export { USER_COLLECTION, MOVIE_COLLECTION, COMMENT_COLLECTION, RATING_COLLECTION, PERMISSION_DENIED, ACCESS_DENIED, LIKES_COLLECTION}